name: Pull Request Tests

on:
  pull_request:
    branches:
      - main  # Specify the branch where pull requests are merged

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up the programming language environment (Python example)
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.13  # Specify your Python version

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Run tests
      - name: Run tests
        run: |
          pytest tests/  # Run your test suite
        env:
          CI: true

  lint:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up the programming language environment (Node.js example for linting)
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16  # Specify your Node.js version

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Run linting
      - name: Run linting
        run: npm run lint

  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Node.js or other environments if building is necessary
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Build the application
      - name: Build application
        run: npm run build

      # Optional: Verify the build output
      - name: Verify build output
        run: |
          if [ ! -d "dist" ]; then
            echo "Build output directory 'dist' not found!"
            exit 1
          fi
